# File: .github/workflows/workflow.yml

on: [push]

name: LoadTest-CLI-Example

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.46.0
        inlineScript: |
            chmod +x ./create-run-test-yaml.sh 
            ./create-run-test-yaml.sh 
